name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release the Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: Build the Project
        run: zig build
